Repository jsk-ros-pkg/jsk_pr2eus, pull requests merged in 2019-12, with the labels that each got.

#419 [pr2eus_moveit] fix cylinder collision object msg
  pr2eus_moveit/euslisp/collision-object-publisher.l
Labels: PR/MergeOk

#415 [pr2eus] add gain key in :stop-grasp
  pr2eus/pr2-interface.l
Labels: PR/MergeOk, question

#408 Fix tilt laser mux topic for obstacle observation
  pr2eus/pr2-interface.l
Labels: question

#418 [pr2eus] Add correction arg in :move-to-wait
  pr2eus/robot-interface.l
Labels: PR/MergeOk

#416 Upload apt cache
  .travis.yml
Labels: PR/MergeOk

#409 Fix typo move-to-no-wait -> move-to-wait
  pr2eus/robot-interface.l
Labels: PR/MergeOk

#402 Updates to :stop-motion
  pr2eus/robot-interface.l
Labels: PR/MergeOk
